In [1]:
# CS6510 HW 1 Code Skeleton
# Please use this outline to implement your decision tree. You can add any code around this.
import csv
import math
import numpy as np
# Enter You Name Here
myname = "Doe-John-Sharath" # or "Doe-Jane-"

In [2]:
def entropyFun(training_set, column_index, value):
    #print(float(training_set[0][-1]))
    col_data_1= [float(row[column_index]) for row in training_set if float(row[-1])==1]
    col_data_2= [float(row[column_index]) for row in training_set if float(row[-1])==0]

    count_positive_list1= [row for row in col_data_1 if row>= value]
    count_positive_class1= len(count_positive_list1)
    count_negative_class1= len(col_data_1)- count_positive_class1
    
    count_positive_list2= [row for row in col_data_2 if row>= value]
    count_positive_class2= len(count_positive_list2)
    count_negative_class2= len(col_data_2)- count_positive_class2
    
    count_greater= count_positive_class1 + count_positive_class2
    count_lesser = count_negative_class1 + count_negative_class2

    
    prob_greater = float(count_greater/(count_greater+count_lesser))
    prob_lesser = 1- prob_greater

    temp1=1
    temp=1
    if(count_greater>0):
        temp = float(count_positive_class1/ count_greater)
    if(count_lesser>0): 
        temp1 = float(count_negative_class1/ count_lesser)
        
        
#     print(prob_greater)
#     print(prob_lesser)
#     print(temp)
#     print(temp1) 
    if((temp ==0 or temp ==1) and (temp1==0 or temp1==1)):
        entropy_val=0
    elif(temp ==0 or temp==1):
        entropy_val= prob_lesser*(-(temp1*math.log(temp1,2) + (1-temp1)*math.log((1-temp1),2)))
    elif(temp1== 0 or temp1==1):
        entropy_val= prob_greater*(-(temp*math.log(temp,2) + (1-temp)*math.log((1-temp),2)))
    else:
        entropy_val=float((prob_greater*(-(temp*math.log(temp,2) + (1-temp)*math.log((1-temp),2)))+prob_lesser*(-(temp1*math.log(temp1,2) + (1-temp1)*math.log((1-temp1),2)))))
    return entropy_val

In [3]:
def findSplit(training_set,entropy):
    local_entropy=0
    local_column=None
    best_entropy=1
    best_column=None
    col_mean_final=0
    '''if entropy==2:
        entropy= calculateInitialEntropy(training_set)
    '''
    for col in range(0,len(training_set[0])-1):
        
        col_data= [float(row[col]) for row in training_set]
        col_mean=float(np.sum(col_data)/len(col_data))
        
        local_entropy= entropyFun(training_set,col,col_mean)
        #print("Local entropy for column ",col," is", local_entropy," with value ",col_mean)
        
        if local_entropy< best_entropy:  
            best_entropy=local_entropy
            best_column = col
            col_mean_final=col_mean

    
    return  best_entropy,best_column,col_mean_final

In [4]:
def partition(training_set, column_index, value):
    true_rows= [row for row in training_set if float(row[column_index]) >= value]
    false_rows = [row for row in training_set if float(row[column_index])< value]
    return true_rows, false_rows

In [5]:
'''def calculateInitialEntropy(training_set):
    col_data_1= len([row for row in training_set if float(row[-1])==1])
    col_data_2= len([row for row in training_set if float(row[-1])==0])
    prob_col_data_1= float(col_data_1/(col_data_2+col_data_1))
    entropy= -(prob_col_data_1*math.log(prob_col_data_1,2) + (1-prob_col_data_1)*(math.log((1-prob_col_data_1),2)))
    return entropy'''

'def calculateInitialEntropy(training_set):\n    col_data_1= len([row for row in training_set if float(row[-1])==1])\n    col_data_2= len([row for row in training_set if float(row[-1])==0])\n    prob_col_data_1= float(col_data_1/(col_data_2+col_data_1))\n    entropy= -(prob_col_data_1*math.log(prob_col_data_1,2) + (1-prob_col_data_1)*(math.log((1-prob_col_data_1),2)))\n    return entropy'

In [6]:
def getClass(training_set, column_index,value):
    true_label= None
    false_label=None
    true_rows= [row for row in training_set if float(row[column_index]) >= value]
    false_rows = [row for row in training_set if float(row[column_index])< value]
    if len(true_rows)>0:
        true_label = true_rows[0][-1]
    if len(false_rows)>0:
        false_label= false_rows[0][-1]
    print(type(false_label))
    print(type(true_label))
    if false_label=="1":
        false_label="class1"
    if true_label=="0":
        true_label="class0"
    if false_label=="0":
        false_label="class0"
    if true_label=="1":
        true_label="class1"
    print("For column ",column_index," with value",value ,"we have the true and false labels as",true_label, false_label)
    return true_label,false_label

In [7]:
class DecisionTree():
    tree = {}

    def learn(self, training_set,index, entropy):
        #implement this function
        value=0
        true_index=0
        false_index=0
        entropy,column_name,value = findSplit(training_set,entropy)
        #print("Entropy of column ",column_name," is ",entropy)
        #check terminating criteria
        if entropy==0:
            print("Base case for index ",index," column ",column_name)
            return getClass(training_set, column_name, value)
        # get the true and false rows based on the criteria
        true_rows, false_rows = partition(training_set,column_name,value)
        
        
        print("True rows of col ",column_name, "of index ",index)
        #print(true_rows)
        true_index= self.learn(true_rows, 2*index,entropy)
        
        print("false rows of col ",column_name," of index ",index)
        false_index= self.learn(false_rows,2*index+1, entropy)
        
        #print("True_Index for index ", index,true_index)
        #print("False_Index for index ",index, false_index)
        
        self.tree[index]=[column_name,value,{"true_rows":true_index,"false_rows":false_index}]
        return index
    #implement this function


    def classify(self, test_instance):
        result = 0 # baseline: always classifies as 0
        #print(self.tree)
        print(self.tree)
        return result

In [8]:
def run_decision_tree():

    # Load data set
    with open("assign1-q1-data.csv") as f:
        next(f, None)
        data = [tuple(line) for line in csv.reader(f, delimiter=",")]
    print("Number of records: %d" % len(data))

    # Split training/test sets
    # You need to modify the following code for cross validation.
    K = 10
    training_set = [x for i, x in enumerate(data) if i % K != 9]
    test_set = [x for i, x in enumerate(data) if i % K == 9]
    
    columns_set={}
    tree = DecisionTree()
    # Construct a tree using training set
    tree.learn( training_set,1,2)
    #print(tree)
    # Classify the test set using the tree we just constructed
    results = []
    #for instance in test_set:
        #result = tree.classify( instance[:-1] ) # prints all values except the last one
        #results.append( result == instance[-1])
    tree.classify(training_set)
    # Accuracy
    #accuracy = float(results.count(True))/float(len(results))
    #print("accuracy: %.4f" % accuracy)       
    

    # Writing results to a file (DO NOT CHANGE)
    #f = open(myname+"result.txt", "w")
    #f.write("accuracy: %.4f" % accuracy)
    #f.close()

In [9]:
if __name__ == "__main__":
    run_decision_tree()

Number of records: 4898
True rows of col  10 of index  1
True rows of col  10 of index  2
True rows of col  10 of index  4
True rows of col  5 of index  8
True rows of col  9 of index  16
True rows of col  8 of index  32
True rows of col  1 of index  64
True rows of col  4 of index  128
Base case for index  256  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.033333333333334 we have the true and false labels as class1 class1
false rows of col  4  of index  128
Base case for index  257  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.26 we have the true and false labels as class1 class0
false rows of col  1  of index  64
True rows of col  2 of index  129
True rows of col  3 of index  258
Base case for index  516  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.2 we have the true and false labels as class1 class0
false rows of col  3  of index  258
Base case for index  517  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.375 we have the true and false labels as class0 class0
false rows of col  2  of index  129
True rows of col  8 of index  259
True rows of col  2 of index  518
Base case for index  1036  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.159999999999999 we have the true and false labels as class1 class1
false rows of col  2  of index  518
Base case for index  1037  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.766666666666667 we have the true and false labels as class1 class0
false rows of col  8  of index  259
True rows of col  8 of index  519
Base case for index  1038  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.0249999999999995 we have the true and false labels as class0 class0
false rows of col  8  of index  519
True rows of col  0 of index  1039
Base case for index  2078  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.933333333333334 we have the true and false labels as class1 class0
false rows of col  0  of index  1039
Base case for index  2079  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.5 we have the true and false labels as class1 class1
false rows of col  8  of index  32
True rows of col  6 of index  65
True rows of col  8 of index  130
True rows of col  0 of index  260
True rows of col  1 of index  520
Base case for index  1040  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.15 we have the true and false labels as class1 class0
false rows of col  1  of index  520
Base case for index  1041  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.75 we have the true and false labels as class0 class0
false rows of col  0  of index  260
Base case for index  521  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.666666666666667 we have the true and false labels as class1 class1
false rows of col  8  of index  130
Base case for index  261  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.8999999999999995 we have the true and false labels as class1 class1
false rows of col  6  of index  65
True rows of col  2 of index  131
True rows of col  6 of index  262
Base case for index  524  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.183333333333334 we have the true and false labels as class1 class1
false rows of col  6  of index  262
True rows of col  0 of index  525
Base case for index  1050  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.65 we have the true and false labels as class1 class1
false rows of col  0  of index  525
Base case for index  1051  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.1 we have the true and false labels as class1 class0
false rows of col  2  of index  131
Base case for index  263  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.246666666666668 we have the true and false labels as class1 class1
false rows of col  9  of index  16
True rows of col  6 of index  33
True rows of col  4 of index  66
True rows of col  9 of index  132
True rows of col  7 of index  264
Base case for index  528  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.325 we have the true and false labels as class1 class1
false rows of col  7  of index  264
True rows of col  2 of index  529
Base case for index  1058  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.6 we have the true and false labels as class0 None
false rows of col  2  of index  529
True rows of col  7 of index  1059
True rows of col  0 of index  2118
Base case for index  4236  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7 we have the true and false labels as class1 class0
false rows of col  0  of index  2118
Base case for index  4237  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.0 we have the true and false labels as class0 None
false rows of col  7  of index  1059
Base case for index  2119  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.433333333333334 we have the true and false labels as class1 class1
false rows of col  9  of index  132
True rows of col  4 of index  265
Base case for index  530  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.716666666666666 we have the true and false labels as class0 class0
false rows of col  4  of index  265
Base case for index  531  column  7
<class 'str'>
<class 'str'>
For column  7  with value 0.9898725 we have the true and false labels as class0 class1
false rows of col  4  of index  66
True rows of col  9 of index  133
True rows of col  2 of index  266
True rows of col  0 of index  532
Base case for index  1064  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.325000000000001 we have the true and false labels as class1 class1
false rows of col  0  of index  532
Base case for index  1065  column  9
<class 'str'>
<class 'str'>
For column  9  with value 0.41 we have the true and false labels as class0 class1
false rows of col  2  of index  266
Base case for index  533  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.211111111111111 we have the true and false labels as class1 class1
false rows of col  9  of index  133
Base case for index  267  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.01 we have the true and false labels as class1 class1
false rows of col  6  of index  33
True rows of col  3 of index  67
True rows of col  6 of index  134
True rows of col  4 of index  268
Base case for index  536  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.566666666666667 we have the true and false labels as class0 class0
false rows of col  4  of index  268
Base case for index  537  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.2 we have the true and false labels as class0 class1
false rows of col  6  of index  134
Base case for index  269  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.042857142857143 we have the true and false labels as class1 class1
false rows of col  3  of index  67
True rows of col  7 of index  135
True rows of col  0 of index  270
True rows of col  0 of index  540
Base case for index  1080  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.75 we have the true and false labels as class0 class0
false rows of col  0  of index  540
True rows of col  0 of index  1081
Base case for index  2162  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.32666666666666666 we have the true and false labels as class0 class1
false rows of col  0  of index  1081
Base case for index  2163  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.099999999999999 we have the true and false labels as class1 None
false rows of col  0  of index  270
True rows of col  1 of index  541
Base case for index  1082  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.414285714285714 we have the true and false labels as class0 class0
false rows of col  1  of index  541
Base case for index  1083  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.775 we have the true and false labels as class0 class1
false rows of col  7  of index  135
True rows of col  0 of index  271
True rows of col  2 of index  542
True rows of col  0 of index  1084
Base case for index  2168  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.30500000000000005 we have the true and false labels as class1 class0
false rows of col  0  of index  1084
Base case for index  2169  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.15 we have the true and false labels as class0 class0
false rows of col  2  of index  542
Base case for index  1085  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.542857142857144 we have the true and false labels as class1 class1
false rows of col  0  of index  271
True rows of col  3 of index  543
Base case for index  1086  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.3 we have the true and false labels as class1 class0
false rows of col  3  of index  543
Base case for index  1087  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.766666666666667 we have the true and false labels as class0 class0
false rows of col  5  of index  8
True rows of col  5 of index  17
True rows of col  3 of index  34
True rows of col  2 of index  68
True rows of col  1 of index  136
Base case for index  272  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.283333333333332 we have the true and false labels as class1 class1
false rows of col  1  of index  136
True rows of col  8 of index  273
Base case for index  546  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.528571428571429 we have the true and false labels as class1 class1
false rows of col  8  of index  273
Base case for index  547  column  1
<class 'str'>
<class 'str'>

For column  1  with value 0.27166666666666667 we have the true and false labels as class1 class0
false rows of col  2  of index  68
True rows of col  7 of index  137
True rows of col  3 of index  274
Base case for index  548  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.959999999999999 we have the true and false labels as class0 class0
false rows of col  3  of index  274
Base case for index  549  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.4033333333333333 we have the true and false labels as class0 class1
false rows of col  7  of index  137
True rows of col  0 of index  275
Base case for index  550  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.628571428571428 we have the true and false labels as class1 class1
false rows of col  0  of index  275
Base case for index  551  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.875 we have the true and false labels as class1 class0
false rows of col  3  of index  34
True rows of col  4 of index  69
True rows of col  3 of index  138
True rows of col  5 of index  276
True rows of col  3 of index  552
Base case for index  1104  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.3999999999999995 we have the true and false labels as class0 class0
false rows of col  3  of index  552
Base case for index  1105  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.3233333333333333 we have the true and false labels as class0 class1
false rows of col  5  of index  276
Base case for index  553  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.0249999999999995 we have the true and false labels as class1 class1
false rows of col  3  of index  138
Base case for index  277  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.872727272727272 we have the true and false labels as class0 class0
false rows of col  4  of index  69
True rows of col  1 of index  139
True rows of col  3 of index  278
True rows of col  0 of index  556
Base case for index  1112  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.26 we have the true and false labels as class0 class1
false rows of col  0  of index  556
Base case for index  1113  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.25 we have the true and false labels as class0 class0
false rows of col  3  of index  278
Base case for index  557  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.418181818181818 we have the true and false labels as class1 class1
false rows of col  1  of index  139
True rows of col  10 of index  279
True rows of col  0 of index  558
True rows of col  2 of index  1116
Base case for index  2232  column  5
<class 'str'>
<class 'str'>
For column  5  with value 26.666666666666668 we have the true and false labels as class1 class0
false rows of col  2  of index  1116
Base case for index  2233  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.0 we have the true and false labels as class0 class0
false rows of col  0  of index  558
Base case for index  1117  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.375 we have the true and false labels as class1 class1
false rows of col  10  of index  279
True rows of col  3 of index  559
Base case for index  1118  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.1522222222222225 we have the true and false labels as class1 class0
false rows of col  3  of index  559
True rows of col  7 of index  1119
Base case for index  2238  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.9399999999999995 we have the true and false labels as class0 class0
false rows of col  7  of index  1119
Base case for index  2239  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.75 we have the true and false labels as class0 class1
false rows of col  5  of index  17
True rows of col  0 of index  35
True rows of col  8 of index  70
True rows of col  4 of index  140
True rows of col  7 of index  280
True rows of col  2 of index  560
Base case for index  1120  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.639999999999999 we have the true and false labels as class0 class0
false rows of col  2  of index  560
Base case for index  1121  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.21666666666666667 we have the true and false labels as class1 class0
false rows of col  7  of index  280
True rows of col  2 of index  561
Base case for index  1122  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.833333333333333 we have the true and false labels as class1 class1
false rows of col  2  of index  561
Base case for index  1123  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.044 we have the true and false labels as class1 class0
false rows of col  4  of index  140
True rows of col  3 of index  281
True rows of col  10 of index  562
Base case for index  1124  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.65 we have the true and false labels as class1 class1
false rows of col  10  of index  562
True rows of col  0 of index  1125
Base case for index  2250  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.35 we have the true and false labels as class1 class0
false rows of col  0  of index  1125
Base case for index  2251  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.6499999999999995 we have the true and false labels as class0 class0
false rows of col  3  of index  281
True rows of col  3 of index  563
Base case for index  1126  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.38000000000000006 we have the true and false labels as class0 class1
false rows of col  3  of index  563
Base case for index  1127  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.675 we have the true and false labels as class0 class0
false rows of col  8  of index  70
True rows of col  9 of index  141
Base case for index  282  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.235714285714285 we have the true and false labels as class0 class0
false rows of col  9  of index  141
True rows of col  4 of index  283
Base case for index  566  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.233333333333334 we have the true and false labels as class0 class0
false rows of col  4  of index  283
True rows of col  2 of index  567
Base case for index  1134  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 8.8 we have the true and false labels as class1 None
false rows of col  2  of index  567
True rows of col  2 of index  1135
Base case for index  2270  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.260000000000001 we have the true and false labels as class0 class0
false rows of col  2  of index  1135
Base case for index  2271  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.116666666666667 we have the true and false labels as class1 class0
false rows of col  0  of index  35
True rows of col  7 of index  71
True rows of col  4 of index  142
True rows of col  7 of index  284
Base case for index  568  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.8500000000000005 we have the true and false labels as class1 class1
false rows of col  7  of index  284
Base case for index  569  column  10
<class 'str'>
<class 'str'>
For column  10  with value 12.9 we have the true and false labels as class1 class0
false rows of col  4  of index  142
True rows of col  1 of index  285
Base case for index  570  column  7
<class 'str'>
<class 'str'>
For column  7  with value 0.9918833333333333 we have the true and false labels as class0 class1
false rows of col  1  of index  285
Base case for index  571  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.25 we have the true and false labels as class0 class0
false rows of col  7  of index  71
True rows of col  5 of index  143
True rows of col  1 of index  286
Base case for index  572  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.71 we have the true and false labels as class1 class1
false rows of col  1  of index  286
True rows of col  9 of index  573
Base case for index  1146  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.05 we have the true and false labels as class0 class0
false rows of col  9  of index  573
True rows of col  5 of index  1147
Base case for index  2294  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.8500000000000005 we have the true and false labels as class1 class1
false rows of col  5  of index  1147
Base case for index  2295  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.550000000000001 we have the true and false labels as class0 class1
false rows of col  5  of index  143
True rows of col  7 of index  287
True rows of col  5 of index  574
True rows of col  2 of index  1148
Base case for index  2296  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.29000000000000004 we have the true and false labels as class0 class1
false rows of col  2  of index  1148
Base case for index  2297  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.6 we have the true and false labels as class0 class0
false rows of col  5  of index  574
Base case for index  1149  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.033333333333332 we have the true and false labels as class1 class1
false rows of col  7  of index  287
True rows of col  2 of index  575
Base case for index  1150  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.433333333333334 we have the true and false labels as class0 class0
false rows of col  2  of index  575
Base case for index  1151  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.15 we have the true and false labels as class1 class0
false rows of col  10  of index  4
True rows of col  5 of index  9
True rows of col  3 of index  18
True rows of col  1 of index  36
True rows of col  5 of index  72
True rows of col  10 of index  144
True rows of col  3 of index  288
Base case for index  576  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.466666666666666 we have the true and false labels as class1 class1
false rows of col  3  of index  288
True rows of col  4 of index  577
Base case for index  1154  column  10
<class 'str'>
<class 'str'>
For column  10  with value 12.26 we have the true and false labels as class0 class1
false rows of col  4  of index  577
Base case for index  1155  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.5 we have the true and false labels as class0 None
false rows of col  10  of index  144
Base case for index  289  column  6
<class 'str'>
<class 'str'>
For column  6  with value 156.6 we have the true and false labels as class0 class1
false rows of col  5  of index  72
True rows of col  8 of index  145
True rows of col  4 of index  290
True rows of col  8 of index  580
Base case for index  1160  column  5
<class 'str'>
<class 'str'>
For column  5  with value 34.0 we have the true and false labels as class1 class0
false rows of col  8  of index  580
True rows of col  0 of index  1161
Base case for index  2322  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.35000000000000003 we have the true and false labels as class1 class0
false rows of col  0  of index  1161
Base case for index  2323  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.6499999999999995 we have the true and false labels as class1 class1
false rows of col  4  of index  290
Base case for index  581  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.1 we have the true and false labels as class1 class1
false rows of col  8  of index  145
True rows of col  9 of index  291
Base case for index  582  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.305 we have the true and false labels as class0 class1
false rows of col  9  of index  291
True rows of col  6 of index  583
Base case for index  1166  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.1 we have the true and false labels as class1 class1
false rows of col  6  of index  583
Base case for index  1167  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.29 we have the true and false labels as class1 class0
false rows of col  1  of index  36
True rows of col  7 of index  73
True rows of col  1 of index  146
True rows of col  1 of index  292
True rows of col  6 of index  584
Base case for index  1168  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.25 we have the true and false labels as class0 class1
false rows of col  6  of index  584
Base case for index  1169  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.766666666666666 we have the true and false labels as class0 class0
false rows of col  1  of index  292
Base case for index  585  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7 we have the true and false labels as class1 class0
false rows of col  1  of index  146
True rows of col  5 of index  293
True rows of col  1 of index  586
Base case for index  1172  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.833333333333333 we have the true and false labels as class1 class1
false rows of col  1  of index  586
Base case for index  1173  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.7 we have the true and false labels as class0 class1
false rows of col  5  of index  293
Base case for index  587  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.875 we have the true and false labels as class0 class0
false rows of col  7  of index  73
True rows of col  0 of index  147
True rows of col  2 of index  294
Base case for index  588  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.125 we have the true and false labels as class0 class0
false rows of col  2  of index  294
True rows of col  10 of index  589
True rows of col  6 of index  1178
Base case for index  2356  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.0 we have the true and false labels as class0 None
false rows of col  6  of index  1178
Base case for index  2357  column  5
<class 'str'>
<class 'str'>
For column  5  with value 36.25 we have the true and false labels as class1 class0
false rows of col  10  of index  589
Base case for index  1179  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.85 we have the true and false labels as class1 class1
false rows of col  0  of index  147
True rows of col  10 of index  295
Base case for index  590  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.9 we have the true and false labels as class1 class1
false rows of col  10  of index  295
True rows of col  2 of index  591
Base case for index  1182  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.133333333333333 we have the true and false labels as class1 class1
false rows of col  2  of index  591
Base case for index  1183  column  5
<class 'str'>
<class 'str'>
For column  5  with value 40.0 we have the true and false labels as class0 class1
false rows of col  3  of index  18
True rows of col  9 of index  37
True rows of col  2 of index  74
True rows of col  10 of index  148
Base case for index  296  column  5
<class 'str'>
<class 'str'>
For column  5  with value 38.8 we have the true and false labels as class1 class0
false rows of col  10  of index  148
Base case for index  297  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.9875 we have the true and false labels as class0 class0
false rows of col  2  of index  74
True rows of col  8 of index  149
True rows of col  0 of index  298
Base case for index  596  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.344444444444445 we have the true and false labels as class1 class1
false rows of col  0  of index  298

True rows of col  5 of index  597
Base case for index  1194  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.4 we have the true and false labels as class1 class1
false rows of col  5  of index  597
Base case for index  1195  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.325 we have the true and false labels as class0 class1
false rows of col  8  of index  149
True rows of col  0 of index  299
True rows of col  5 of index  598
Base case for index  1196  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.128 we have the true and false labels as class0 class1
false rows of col  5  of index  598
True rows of col  0 of index  1197
Base case for index  2394  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.1725 we have the true and false labels as class1 class0
false rows of col  0  of index  1197
Base case for index  2395  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.475 we have the true and false labels as class0 class0
false rows of col  0  of index  299
True rows of col  4 of index  599
Base case for index  1198  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.75 we have the true and false labels as class1 class0
false rows of col  4  of index  599
Base case for index  1199  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.675000000000001 we have the true and false labels as class1 class1
false rows of col  9  of index  37
True rows of col  0 of index  75
True rows of col  4 of index  150
True rows of col  0 of index  300
Base case for index  600  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.0 we have the true and false labels as class0 class0
false rows of col  0  of index  300
True rows of col  5 of index  601
True rows of col  2 of index  1202
Base case for index  2404  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.199999999999999 we have the true and false labels as class1 class0
false rows of col  2  of index  1202
Base case for index  2405  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.159999999999999 we have the true and false labels as class0 class0
false rows of col  5  of index  601
True rows of col  1 of index  1203
Base case for index  2406  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.9 we have the true and false labels as class1 class1
false rows of col  1  of index  1203
Base case for index  2407  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.133333333333333 we have the true and false labels as class1 class0
false rows of col  4  of index  150
True rows of col  8 of index  301
True rows of col  2 of index  602
Base case for index  1204  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.9 we have the true and false labels as class0 class1
false rows of col  2  of index  602
Base case for index  1205  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.160000000000001 we have the true and false labels as class1 class1
false rows of col  8  of index  301
True rows of col  0 of index  603
True rows of col  7 of index  1206
Base case for index  2412  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.566666666666666 we have the true and false labels as class1 class1
false rows of col  7  of index  1206
True rows of col  0 of index  2413
Base case for index  4826  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.8 we have the true and false labels as class1 None
false rows of col  0  of index  2413
Base case for index  4827  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.5 we have the true and false labels as class0 class1
false rows of col  0  of index  603
Base case for index  1207  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.274 we have the true and false labels as class0 class1
false rows of col  0  of index  75
True rows of col  4 of index  151
True rows of col  8 of index  302
Base case for index  604  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.918181818181818 we have the true and false labels as class0 class0
false rows of col  8  of index  302
True rows of col  2 of index  605
Base case for index  1210  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3 we have the true and false labels as class0 class0
false rows of col  2  of index  605
Base case for index  1211  column  6
<class 'str'>
<class 'str'>
For column  6  with value 131.75 we have the true and false labels as class1 class0
false rows of col  4  of index  151
True rows of col  9 of index  303
True rows of col  1 of index  606
Base case for index  1212  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.35 we have the true and false labels as class1 class1
false rows of col  1  of index  606
True rows of col  0 of index  1213
Base case for index  2426  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.433333333333334 we have the true and false labels as class1 class0
false rows of col  0  of index  1213
Base case for index  2427  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.85 we have the true and false labels as class0 class0
false rows of col  9  of index  303
True rows of col  2 of index  607
Base case for index  1214  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.142857142857143 we have the true and false labels as class0 class0
false rows of col  2  of index  607
Base case for index  1215  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.4925 we have the true and false labels as class0 class1
false rows of col  5  of index  9
True rows of col  5 of index  19
True rows of col  8 of index  38
True rows of col  9 of index  76
True rows of col  10 of index  152
True rows of col  4 of index  304
True rows of col  1 of index  608
True rows of col  1 of index  1216
Base case for index  2432  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.3233333333333333 we have the true and false labels as class0 class1
false rows of col  1  of index  1216
Base case for index  2433  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.4 we have the true and false labels as class0 None
false rows of col  1  of index  608
Base case for index  1217  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.85 we have the true and false labels as class1 class1
false rows of col  4  of index  304
Base case for index  609  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.710000000000001 we have the true and false labels as class1 class1
false rows of col  10  of index  152
True rows of col  1 of index  305
True rows of col  8 of index  610
Base case for index  1220  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.6000000000000005 we have the true and false labels as class0 class0
false rows of col  8  of index  610
Base case for index  1221  column  9
<class 'str'>
<class 'str'>
For column  9  with value 0.575 we have the true and false labels as class1 class0
false rows of col  1  of index  305
True rows of col  4 of index  611
Base case for index  1222  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.4 we have the true and false labels as class0 None
false rows of col  4  of index  611
True rows of col  7 of index  1223
Base case for index  2446  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.15 we have the true and false labels as class0 class1
false rows of col  7  of index  1223
Base case for index  2447  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.050000000000001 we have the true and false labels as class1 class1
false rows of col  9  of index  76
True rows of col  3 of index  153
True rows of col  3 of index  306
True rows of col  4 of index  612
Base case for index  1224  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4 we have the true and false labels as class1 class0
false rows of col  4  of index  612
Base case for index  1225  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.925000000000001 we have the true and false labels as class0 class0
false rows of col  3  of index  306
True rows of col  1 of index  613
Base case for index  1226  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.014285714285713 we have the true and false labels as class1 class1
false rows of col  1  of index  613
Base case for index  1227  column  10
<class 'str'>
<class 'str'>
For column  10  with value 11.940000000000001 we have the true and false labels as class1 class0
false rows of col  3  of index  153
True rows of col  3 of index  307
True rows of col  1 of index  614
Base case for index  1228  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.08 we have the true and false labels as class1 class0
false rows of col  1  of index  614
Base case for index  1229  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.333333333333333 we have the true and false labels as class0 class1
false rows of col  3  of index  307
True rows of col  3 of index  615
True rows of col  4 of index  1230
Base case for index  2460  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.6000000000000005 we have the true and false labels as class0 class0
false rows of col  4  of index  1230
Base case for index  2461  column  5
<class 'str'>
<class 'str'>
For column  5  with value 25.0 we have the true and false labels as class1 class0
false rows of col  3  of index  615
Base case for index  1231  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.55 we have the true and false labels as class0 class0
false rows of col  8  of index  38
True rows of col  2 of index  77
True rows of col  0 of index  154
True rows of col  0 of index  308
Base case for index  616  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.133333333333333 we have the true and false labels as class0 class0
false rows of col  0  of index  308
True rows of col  1 of index  617
Base case for index  1234  column  7
<class 'str'>
<class 'str'>
For column  7  with value 0.9911249999999999 we have the true and false labels as class0 class1
false rows of col  1  of index  617
Base case for index  1235  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.333333333333333 we have the true and false labels as class0 class0
false rows of col  0  of index  154
True rows of col  5 of index  309
True rows of col  1 of index  618
Base case for index  1236  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.6000000000000005 we have the true and false labels as class1 class1
false rows of col  1  of index  618
True rows of col  8 of index  1237
Base case for index  2474  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4399999999999995 we have the true and false labels as class0 class0
false rows of col  8  of index  1237
Base case for index  2475  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.2 we have the true and false labels as class0 class1
false rows of col  5  of index  309
True rows of col  7 of index  619
Base case for index  1238  column  7
<class 'str'>
<class 'str'>
For column  7  with value 0.9905825 we have the true and false labels as class0 class1
false rows of col  7  of index  619
Base case for index  1239  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4 we have the true and false labels as class1 class1
false rows of col  2  of index  77
True rows of col  0 of index  155
True rows of col  4 of index  310
True rows of col  1 of index  620
True rows of col  0 of index  1240
Base case for index  2480  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.7 we have the true and false labels as class0 class1
false rows of col  0  of index  1240
Base case for index  2481  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.1 we have the true and false labels as class0 None
false rows of col  1  of index  620
Base case for index  1241  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.633333333333333 we have the true and false labels as class0 class0
false rows of col  4  of index  310
True rows of col  0 of index  621
Base case for index  1242  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.55 we have the true and false labels as class0 class0
false rows of col  0  of index  621
True rows of col  2 of index  1243
Base case for index  2486  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.375 we have the true and false labels as class1 class1
false rows of col  2  of index  1243
Base case for index  2487  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.449999999999999 we have the true and false labels as class1 class0
false rows of col  0  of index  155
True rows of col  4 of index  311
True rows of col  3 of index  622
Base case for index  1244  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.459999999999999 we have the true and false labels as class0 class0
false rows of col  3  of index  622
True rows of col  4 of index  1245
Base case for index  2490  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7 we have the true and false labels as class1 class1
false rows of col  4  of index  1245
True rows of col  5 of index  2491
Base case for index  4982  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.25 we have the true and false labels as class1 class0
false rows of col  5  of index  2491
Base case for index  4983  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.5 we have the true and false labels as class0 class0
false rows of col  4  of index  311
Base case for index  623  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.458333333333333 we have the true and false labels as class0 class0
false rows of col  5  of index  19
True rows of col  2 of index  39
True rows of col  5 of index  78
True rows of col  9 of index  156
True rows of col  7 of index  312
Base case for index  624  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.122 we have the true and false labels as class1 class0
false rows of col  7  of index  312
Base case for index  625  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.242857142857143 we have the true and false labels as class0 class0
false rows of col  9  of index  156
True rows of col  9 of index  313
True rows of col  2 of index  626
Base case for index  1252  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.55 we have the true and false labels as class0 class1
false rows of col  2  of index  626
Base case for index  1253  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.8500000000000005 we have the true and false labels as class0 class0
false rows of col  9  of index  313
True rows of col  0 of index  627
Base case for index  1254  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.8999999999999995 we have the true and false labels as class1 class1
false rows of col  0  of index  627
Base case for index  1255  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.75 we have the true and false labels as class0 class1
false rows of col  5  of index  78
True rows of col  3 of index  157
True rows of col  0 of index  314
Base case for index  628  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.2 we have the true and false labels as class0 class0
false rows of col  0  of index  314
Base case for index  629  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.699999999999999 we have the true and false labels as class0 class1
false rows of col  3  of index  157
Base case for index  315  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.127777777777778 we have the true and false labels as class0 class0
false rows of col  2  of index  39
True rows of col  9 of index  79
True rows of col  3 of index  158
True rows of col  5 of index  316
Base case for index  632  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4 we have the true and false labels as class1 class1
false rows of col  5  of index  316
Base case for index  633  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.27 we have the true and false labels as class0 class1
false rows of col  3  of index  158
True rows of col  9 of index  317
Base case for index  634  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.1983333333333337 we have the true and false labels as class1 class0
false rows of col  9  of index  317
Base case for index  635  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.875 we have the true and false labels as class0 class0
false rows of col  9  of index  79
True rows of col  7 of index  159
Base case for index  318  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.157894736842105 we have the true and false labels as class0 class0
false rows of col  7  of index  159
True rows of col  0 of index  319
True rows of col  7 of index  638
Base case for index  1276  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.12 we have the true and false labels as class0 class0
false rows of col  7  of index  638
Base case for index  1277  column  9
<class 'str'>
<class 'str'>
For column  9  with value 0.366 we have the true and false labels as class1 class0
false rows of col  0  of index  319
True rows of col  3 of index  639
Base case for index  1278  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.133333333333333 we have the true and false labels as class1 class1
false rows of col  3  of index  639
True rows of col  0 of index  1279
Base case for index  2558  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3500000000000005 we have the true and false labels as class0 class0
false rows of col  0  of index  1279
Base case for index  2559  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.4875 we have the true and false labels as class1 class0
false rows of col  10  of index  2
True rows of col  4 of index  5
True rows of col  5 of index  10
True rows of col  2 of index  20
True rows of col  1 of index  40
True rows of col  3 of index  80
True rows of col  7 of index  160
True rows of col  8 of index  320
Base case for index  640  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.466666666666666 we have the true and false labels as class0 class1
false rows of col  8  of index  320
Base case for index  641  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.016666666666667 we have the true and false labels as class0 class0
false rows of col  7  of index  160

True rows of col  1 of index  321
Base case for index  642  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.6000000000000005 we have the true and false labels as class1 class1
false rows of col  1  of index  321
True rows of col  0 of index  643
Base case for index  1286  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.6 we have the true and false labels as class0 class1
false rows of col  0  of index  643
Base case for index  1287  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.766666666666667 we have the true and false labels as class0 class0
false rows of col  3  of index  80
True rows of col  8 of index  161
True rows of col  4 of index  322
Base case for index  644  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.666666666666667 we have the true and false labels as class0 class0
false rows of col  4  of index  322
True rows of col  3 of index  645
Base case for index  1290  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.733333333333333 we have the true and false labels as class0 class0
false rows of col  3  of index  645
True rows of col  1 of index  1291
Base case for index  2582  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.0 we have the true and false labels as class1 class0
false rows of col  1  of index  1291
Base case for index  2583  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.25 we have the true and false labels as class1 class1
false rows of col  8  of index  161
Base case for index  323  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.253846153846154 we have the true and false labels as class0 class0
false rows of col  1  of index  40
True rows of col  10 of index  81
True rows of col  5 of index  162
True rows of col  3 of index  324
Base case for index  648  column  5
<class 'str'>
<class 'str'>
For column  5  with value 65.25 we have the true and false labels as class1 class0
false rows of col  3  of index  324
Base case for index  649  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.472222222222222 we have the true and false labels as class1 class1
false rows of col  5  of index  162
True rows of col  10 of index  325
True rows of col  0 of index  650
True rows of col  1 of index  1300
Base case for index  2600  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.0445 we have the true and false labels as class0 class1
false rows of col  1  of index  1300
Base case for index  2601  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.6 we have the true and false labels as class0 None
false rows of col  0  of index  650
Base case for index  1301  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.433333333333334 we have the true and false labels as class1 class1
false rows of col  10  of index  325
Base case for index  651  column  10
<class 'str'>
<class 'str'>
For column  10  with value 11.149999999999999 we have the true and false labels as class1 class0
false rows of col  10  of index  81
True rows of col  8 of index  163
True rows of col  0 of index  326
Base case for index  652  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.46749999999999997 we have the true and false labels as class0 class1
false rows of col  0  of index  326
Base case for index  653  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.300000000000001 we have the true and false labels as class0 class0
false rows of col  8  of index  163
True rows of col  10 of index  327
Base case for index  654  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.38125 we have the true and false labels as class0 class1
false rows of col  10  of index  327
Base case for index  655  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.042333333333333334 we have the true and false labels as class1 class0
false rows of col  2  of index  20
True rows of col  4 of index  41
True rows of col  1 of index  82
Base case for index  164  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.611111111111111 we have the true and false labels as class0 class0
false rows of col  1  of index  82
True rows of col  5 of index  165
Base case for index  330  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.62 we have the true and false labels as class0 class0
false rows of col  5  of index  165
True rows of col  2 of index  331
True rows of col  2 of index  662
Base case for index  1324  column  3
<class 'str'>
<class 'str'>
For column  3  with value 2.9250000000000003 we have the true and false labels as class1 class0
false rows of col  2  of index  662
True rows of col  5 of index  1325
True rows of col  9 of index  2650
Base case for index  5300  column  5
<class 'str'>
<class 'str'>
For column  5  with value 41.25 we have the true and false labels as class1 class0
false rows of col  9  of index  2650
Base case for index  5301  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.6 we have the true and false labels as class1 None
false rows of col  5  of index  1325
Base case for index  2651  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.949999999999999 we have the true and false labels as class1 class1
false rows of col  2  of index  331
Base case for index  663  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.200000000000001 we have the true and false labels as class0 class0
false rows of col  4  of index  41
True rows of col  3 of index  83
True rows of col  1 of index  166
True rows of col  9 of index  332
True rows of col  3 of index  664
Base case for index  1328  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.04066666666666666 we have the true and false labels as class0 class1
false rows of col  3  of index  664
Base case for index  1329  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.2 we have the true and false labels as class0 class0
false rows of col  9  of index  332
True rows of col  0 of index  665
True rows of col  1 of index  1330
Base case for index  2660  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.35 we have the true and false labels as class1 class0
false rows of col  1  of index  1330
Base case for index  2661  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7 we have the true and false labels as class0 class0
false rows of col  0  of index  665
Base case for index  1331  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.27375000000000005 we have the true and false labels as class1 class0
false rows of col  1  of index  166
True rows of col  2 of index  333
Base case for index  666  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.414285714285713 we have the true and false labels as class0 class0
false rows of col  2  of index  333
True rows of col  9 of index  667
Base case for index  1334  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.1 we have the true and false labels as class1 class0
false rows of col  9  of index  667
Base case for index  1335  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.633333333333333 we have the true and false labels as class0 class0
false rows of col  3  of index  83
True rows of col  7 of index  167
True rows of col  7 of index  334
True rows of col  2 of index  668
Base case for index  1336  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.450000000000001 we have the true and false labels as class0 class0
false rows of col  2  of index  668
Base case for index  1337  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.245 we have the true and false labels as class1 class0
false rows of col  7  of index  334
True rows of col  4 of index  669
Base case for index  1338  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3500000000000005 we have the true and false labels as class1 class1
false rows of col  4  of index  669
True rows of col  0 of index  1339
Base case for index  2678  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.3500000000000005 we have the true and false labels as class1 class0
false rows of col  0  of index  1339
Base case for index  2679  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.333333333333333 we have the true and false labels as class1 class1
false rows of col  7  of index  167
True rows of col  5 of index  335
Base case for index  670  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.423076923076923 we have the true and false labels as class0 class0
false rows of col  5  of index  335
True rows of col  1 of index  671
Base case for index  1342  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.945454545454544 we have the true and false labels as class0 class1
false rows of col  1  of index  671
Base case for index  1343  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.366666666666666 we have the true and false labels as class0 class0
false rows of col  5  of index  10
True rows of col  5 of index  21
True rows of col  9 of index  42
True rows of col  1 of index  84
True rows of col  2 of index  168
True rows of col  6 of index  336
True rows of col  6 of index  672
True rows of col  1 of index  1344
Base case for index  2688  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.4 we have the true and false labels as class1 class1
false rows of col  1  of index  1344
Base case for index  2689  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.41 we have the true and false labels as class1 class0
false rows of col  6  of index  672
Base case for index  1345  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.700000000000001 we have the true and false labels as class0 class0
false rows of col  6  of index  336
True rows of col  1 of index  673
Base case for index  1346  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.95 we have the true and false labels as class1 class0
false rows of col  1  of index  673
Base case for index  1347  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.0249999999999995 we have the true and false labels as class1 class1
false rows of col  2  of index  168
True rows of col  0 of index  337
True rows of col  10 of index  674
Base case for index  1348  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.225 we have the true and false labels as class1 class1
false rows of col  10  of index  674
True rows of col  5 of index  1349
Base case for index  2698  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.26666666666666666 we have the true and false labels as class1 class0
false rows of col  5  of index  1349
Base case for index  2699  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.225 we have the true and false labels as class0 class0
false rows of col  0  of index  337
True rows of col  1 of index  675
Base case for index  1350  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.43 we have the true and false labels as class1 class0
false rows of col  1  of index  675
Base case for index  1351  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.033333333333334 we have the true and false labels as class0 class0
false rows of col  1  of index  84
True rows of col  5 of index  169
True rows of col  2 of index  338
True rows of col  6 of index  676
True rows of col  0 of index  1352
Base case for index  2704  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.566666666666667 we have the true and false labels as class0 class0
false rows of col  0  of index  1352
Base case for index  2705  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.0 we have the true and false labels as class1 class0
false rows of col  6  of index  676
Base case for index  1353  column  3
<class 'str'>
<class 'str'>
For column  3  with value 2.0749999999999997 we have the true and false labels as class1 class0
false rows of col  2  of index  338
True rows of col  3 of index  677
True rows of col  0 of index  1354
Base case for index  2708  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.9 we have the true and false labels as class0 class0
false rows of col  0  of index  1354
Base case for index  2709  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.2 we have the true and false labels as class1 class0
false rows of col  3  of index  677
Base case for index  1355  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.485714285714286 we have the true and false labels as class0 class0
false rows of col  5  of index  169
True rows of col  9 of index  339
Base case for index  678  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.55 we have the true and false labels as class1 class0
false rows of col  9  of index  339
Base case for index  679  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.054545454545454 we have the true and false labels as class0 class0
false rows of col  9  of index  42
True rows of col  9 of index  85
True rows of col  7 of index  170
True rows of col  6 of index  340
True rows of col  9 of index  680
True rows of col  1 of index  1360
Base case for index  2720  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.8999999999999995 we have the true and false labels as class1 class0
false rows of col  1  of index  1360
Base case for index  2721  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.2 we have the true and false labels as class0 class0
false rows of col  9  of index  680
Base case for index  1361  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.8999999999999995 we have the true and false labels as class1 class1
false rows of col  6  of index  340
True rows of col  2 of index  681
Base case for index  1362  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.18 we have the true and false labels as class0 class0
false rows of col  2  of index  681
True rows of col  1 of index  1363
Base case for index  2726  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.375 we have the true and false labels as class1 class0
false rows of col  1  of index  1363
Base case for index  2727  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.25 we have the true and false labels as class0 class0
false rows of col  7  of index  170
True rows of col  9 of index  341
True rows of col  4 of index  682
True rows of col  0 of index  1364
Base case for index  2728  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.051666666666666666 we have the true and false labels as class0 class1
false rows of col  0  of index  1364
Base case for index  2729  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.8 we have the true and false labels as class1 class1
false rows of col  4  of index  682
Base case for index  1365  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.833333333333333 we have the true and false labels as class0 class0
false rows of col  9  of index  341
Base case for index  683  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.74 we have the true and false labels as class0 class0
false rows of col  9  of index  85
True rows of col  3 of index  171
Base case for index  342  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.67 we have the true and false labels as class0 class0
false rows of col  3  of index  171
True rows of col  4 of index  343
Base case for index  686  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.033333333333332 we have the true and false labels as class0 class0
false rows of col  4  of index  343
True rows of col  4 of index  687
True rows of col  4 of index  1374
Base case for index  2748  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.5033333333333333 we have the true and false labels as class0 class1
false rows of col  4  of index  1374
Base case for index  2749  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.2 we have the true and false labels as class0 None
false rows of col  4  of index  687
Base case for index  1375  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.12 we have the true and false labels as class0 class0
false rows of col  5  of index  21
True rows of col  1 of index  43
True rows of col  3 of index  86
True rows of col  10 of index  172
True rows of col  3 of index  344
Base case for index  688  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.2966666666666667 we have the true and false labels as class0 class1
false rows of col  3  of index  344
Base case for index  689  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.675000000000001 we have the true and false labels as class0 class0
false rows of col  10  of index  172
Base case for index  345  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.918181818181818 we have the true and false labels as class0 class0
false rows of col  3  of index  86
Base case for index  173  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.01578947368421 we have the true and false labels as class0 class0
false rows of col  1  of index  43
True rows of col  1 of index  87
True rows of col  7 of index  174
True rows of col  6 of index  348
Base case for index  696  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.5625 we have the true and false labels as class0 class0
false rows of col  6  of index  348
True rows of col  10 of index  697
Base case for index  1394  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.9 we have the true and false labels as class0 None
false rows of col  10  of index  697
Base case for index  1395  column  5
<class 'str'>
<class 'str'>
For column  5  with value 16.5 we have the true and false labels as class1 class0
false rows of col  7  of index  174

Base case for index  349  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.9319999999999995 we have the true and false labels as class0 class0
false rows of col  1  of index  87
True rows of col  2 of index  175
True rows of col  9 of index  350
Base case for index  700  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.15000000000000002 we have the true and false labels as class0 class1
false rows of col  9  of index  350
Base case for index  701  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.625 we have the true and false labels as class0 class0
false rows of col  2  of index  175
True rows of col  9 of index  351
True rows of col  9 of index  702
Base case for index  1404  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.6 we have the true and false labels as class0 class1
false rows of col  9  of index  702
Base case for index  1405  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.628571428571428 we have the true and false labels as class0 class0
false rows of col  9  of index  351
True rows of col  8 of index  703
True rows of col  3 of index  1406
Base case for index  2812  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.2 we have the true and false labels as class0 class1
false rows of col  3  of index  1406
Base case for index  2813  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.88 we have the true and false labels as class1 class1
false rows of col  8  of index  703
True rows of col  3 of index  1407
Base case for index  2814  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.15 we have the true and false labels as class0 class1
false rows of col  3  of index  1407
Base case for index  2815  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.175 we have the true and false labels as class0 class0
false rows of col  4  of index  5
True rows of col  8 of index  11
True rows of col  8 of index  22
True rows of col  0 of index  44
True rows of col  3 of index  88
True rows of col  2 of index  176
Base case for index  352  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.05 we have the true and false labels as class1 class1
false rows of col  2  of index  176
True rows of col  2 of index  353
True rows of col  10 of index  706
Base case for index  1412  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.74 we have the true and false labels as class1 class1
false rows of col  10  of index  706
Base case for index  1413  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.95 we have the true and false labels as class0 class1
false rows of col  2  of index  353
True rows of col  5 of index  707
Base case for index  1414  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.15 we have the true and false labels as class1 class0
false rows of col  5  of index  707
Base case for index  1415  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.85 we have the true and false labels as class0 class0
false rows of col  3  of index  88
True rows of col  0 of index  177
True rows of col  5 of index  354
True rows of col  7 of index  708
Base case for index  1416  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.260000000000001 we have the true and false labels as class1 class1
false rows of col  7  of index  708
True rows of col  0 of index  1417
Base case for index  2834  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.033333333333334 we have the true and false labels as class0 class1
false rows of col  0  of index  1417
Base case for index  2835  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.6 we have the true and false labels as class0 None
false rows of col  5  of index  354
True rows of col  10 of index  709
Base case for index  1418  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.75 we have the true and false labels as class1 class0
false rows of col  10  of index  709
Base case for index  1419  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.0 we have the true and false labels as class0 class0
false rows of col  0  of index  177
True rows of col  7 of index  355
True rows of col  1 of index  710
Base case for index  1420  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.1 we have the true and false labels as class1 None
false rows of col  1  of index  710
Base case for index  1421  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.300000000000001 we have the true and false labels as class1 class0
false rows of col  7  of index  355
True rows of col  3 of index  711
Base case for index  1422  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.262 we have the true and false labels as class1 class0
false rows of col  3  of index  711
Base case for index  1423  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.366666666666667 we have the true and false labels as class1 class1
false rows of col  0  of index  44
True rows of col  1 of index  89
True rows of col  2 of index  178
True rows of col  1 of index  356
True rows of col  2 of index  712
Base case for index  1424  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.7 we have the true and false labels as class1 class1
false rows of col  2  of index  712
Base case for index  1425  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.699999999999999 we have the true and false labels as class1 class0
false rows of col  1  of index  356
True rows of col  0 of index  713
Base case for index  1426  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.295 we have the true and false labels as class1 class0
false rows of col  0  of index  713
Base case for index  1427  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 5.8 we have the true and false labels as class0 None
false rows of col  2  of index  178
True rows of col  8 of index  357
Base case for index  714  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.644444444444445 we have the true and false labels as class0 class0
false rows of col  8  of index  357
True rows of col  1 of index  715
Base case for index  1430  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.3 we have the true and false labels as class0 class0
false rows of col  1  of index  715
Base case for index  1431  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.3125 we have the true and false labels as class1 class0
false rows of col  1  of index  89
True rows of col  1 of index  179
True rows of col  2 of index  358
True rows of col  5 of index  716
Base case for index  1432  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.55 we have the true and false labels as class0 class1
false rows of col  5  of index  716
Base case for index  1433  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.5 we have the true and false labels as class1 class1
false rows of col  2  of index  358
True rows of col  5 of index  717
Base case for index  1434  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.258 we have the true and false labels as class1 class0
false rows of col  5  of index  717
True rows of col  1 of index  1435
Base case for index  2870  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.65 we have the true and false labels as class0 class0
false rows of col  1  of index  1435
Base case for index  2871  column  3
<class 'str'>
<class 'str'>
For column  3  with value 10.533333333333333 we have the true and false labels as class1 class0
false rows of col  1  of index  179
True rows of col  9 of index  359
True rows of col  1 of index  718
Base case for index  1436  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.900000000000001 we have the true and false labels as class1 class0
false rows of col  1  of index  718
Base case for index  1437  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.5 we have the true and false labels as class0 class0
false rows of col  9  of index  359
True rows of col  10 of index  719
Base case for index  1438  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.625 we have the true and false labels as class1 class0
false rows of col  10  of index  719
Base case for index  1439  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.625 we have the true and false labels as class1 class1
false rows of col  8  of index  22
True rows of col  8 of index  45
True rows of col  5 of index  90
True rows of col  2 of index  180
True rows of col  10 of index  360
Base case for index  720  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.03725 we have the true and false labels as class1 class0
false rows of col  10  of index  360
True rows of col  6 of index  721
Base case for index  1442  column  3
<class 'str'>
<class 'str'>
For column  3  with value 3.716666666666667 we have the true and false labels as class1 class0
false rows of col  6  of index  721
True rows of col  1 of index  1443
Base case for index  2886  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.566666666666666 we have the true and false labels as class1 class1
false rows of col  1  of index  1443
Base case for index  2887  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.4 we have the true and false labels as class1 class0
false rows of col  2  of index  180
True rows of col  2 of index  361
Base case for index  722  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.615384615384614 we have the true and false labels as class1 class1
false rows of col  2  of index  361
Base case for index  723  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.28833333333333333 we have the true and false labels as class0 class1
false rows of col  5  of index  90
True rows of col  0 of index  181
True rows of col  8 of index  362
True rows of col  1 of index  724
Base case for index  1448  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7250000000000005 we have the true and false labels as class0 class0
false rows of col  1  of index  724
Base case for index  1449  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.7600000000000002 we have the true and false labels as class0 class1
false rows of col  8  of index  362
Base case for index  725  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.699999999999999 we have the true and false labels as class0 class1
false rows of col  0  of index  181
True rows of col  4 of index  363
True rows of col  0 of index  726
True rows of col  0 of index  1452
Base case for index  2904  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.1 we have the true and false labels as class0 class0
false rows of col  0  of index  1452
Base case for index  2905  column  1
<class 'str'>
<class 'str'>

For column  1  with value 0.3 we have the true and false labels as class0 class1
false rows of col  0  of index  726
Base case for index  1453  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.660000000000001 we have the true and false labels as class0 class0
false rows of col  4  of index  363
True rows of col  4 of index  727
True rows of col  1 of index  1454
Base case for index  2908  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.866666666666667 we have the true and false labels as class1 class0
false rows of col  1  of index  1454
Base case for index  2909  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.633333333333333 we have the true and false labels as class1 class1
false rows of col  4  of index  727
Base case for index  1455  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.65 we have the true and false labels as class0 class0
false rows of col  8  of index  45
True rows of col  10 of index  91
True rows of col  6 of index  182
True rows of col  2 of index  364
True rows of col  5 of index  728
Base case for index  1456  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4799999999999995 we have the true and false labels as class0 class0
false rows of col  5  of index  728
Base case for index  1457  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.30000000000000004 we have the true and false labels as class1 class0
false rows of col  2  of index  364
True rows of col  1 of index  729
True rows of col  3 of index  1458
Base case for index  2916  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.25 we have the true and false labels as class0 class0
false rows of col  3  of index  1458
Base case for index  2917  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.066666666666666 we have the true and false labels as class1 class0
false rows of col  1  of index  729
Base case for index  1459  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.424999999999999 we have the true and false labels as class1 class0
false rows of col  6  of index  182
True rows of col  0 of index  365
True rows of col  8 of index  730
Base case for index  1460  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.949999999999999 we have the true and false labels as class0 class1
false rows of col  8  of index  730
Base case for index  1461  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.625 we have the true and false labels as class0 class0
false rows of col  0  of index  365
Base case for index  731  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.255555555555556 we have the true and false labels as class0 class0
false rows of col  10  of index  91
True rows of col  6 of index  183
Base case for index  366  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.868181818181818 we have the true and false labels as class0 class0
false rows of col  6  of index  183
True rows of col  8 of index  367
Base case for index  734  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.858333333333334 we have the true and false labels as class0 class0
false rows of col  8  of index  367
True rows of col  4 of index  735
True rows of col  7 of index  1470
Base case for index  2940  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.1775 we have the true and false labels as class1 class0
false rows of col  7  of index  1470
Base case for index  2941  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.550000000000001 we have the true and false labels as class0 class0
false rows of col  4  of index  735
Base case for index  1471  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.55 we have the true and false labels as class0 class0
false rows of col  8  of index  11
True rows of col  1 of index  23
True rows of col  0 of index  46
True rows of col  8 of index  92
True rows of col  2 of index  184
True rows of col  5 of index  368
Base case for index  736  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.799999999999999 we have the true and false labels as class0 class0
false rows of col  5  of index  368
Base case for index  737  column  9
<class 'str'>
<class 'str'>
For column  9  with value 0.40750000000000003 we have the true and false labels as class0 class1
false rows of col  2  of index  184
True rows of col  10 of index  369
True rows of col  5 of index  738
Base case for index  1476  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.3 we have the true and false labels as class1 class1
false rows of col  5  of index  738
Base case for index  1477  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.333333333333334 we have the true and false labels as class1 class0
false rows of col  10  of index  369
True rows of col  1 of index  739
Base case for index  1478  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.425 we have the true and false labels as class0 class1
false rows of col  1  of index  739
Base case for index  1479  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.24 we have the true and false labels as class0 class0
false rows of col  8  of index  92
True rows of col  5 of index  185
Base case for index  370  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.16 we have the true and false labels as class0 class0
false rows of col  5  of index  185
True rows of col  1 of index  371
Base case for index  742  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.350000000000001 we have the true and false labels as class0 class0
false rows of col  1  of index  371
True rows of col  1 of index  743
Base case for index  1486  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.2 we have the true and false labels as class1 class0
false rows of col  1  of index  743
Base case for index  1487  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.27 we have the true and false labels as class0 class1
false rows of col  0  of index  46
True rows of col  8 of index  93
True rows of col  7 of index  186
Base case for index  372  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7875 we have the true and false labels as class0 class0
false rows of col  7  of index  186
True rows of col  2 of index  373
True rows of col  4 of index  746
Base case for index  1492  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.0375 we have the true and false labels as class1 class0
false rows of col  4  of index  746
Base case for index  1493  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.8 we have the true and false labels as class0 class0
false rows of col  2  of index  373
True rows of col  4 of index  747
Base case for index  1494  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.742857142857142 we have the true and false labels as class0 class0
false rows of col  4  of index  747
Base case for index  1495  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.029500000000000002 we have the true and false labels as class0 class1
false rows of col  8  of index  93
Base case for index  187  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.712121212121212 we have the true and false labels as class0 class0
false rows of col  1  of index  23
True rows of col  0 of index  47
True rows of col  5 of index  94
True rows of col  9 of index  188
True rows of col  3 of index  376
Base case for index  752  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.15 we have the true and false labels as class0 class0
false rows of col  3  of index  376
Base case for index  753  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.033 we have the true and false labels as class1 class0
false rows of col  9  of index  188
Base case for index  377  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.041176470588237 we have the true and false labels as class0 class0
false rows of col  5  of index  94
True rows of col  9 of index  189
True rows of col  10 of index  378
True rows of col  5 of index  756
Base case for index  1512  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.1466666666666667 we have the true and false labels as class1 class0
false rows of col  5  of index  756
Base case for index  1513  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.58 we have the true and false labels as class0 class0
false rows of col  10  of index  378
Base case for index  757  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.4 we have the true and false labels as class0 class0
false rows of col  9  of index  189
True rows of col  5 of index  379
True rows of col  2 of index  758
Base case for index  1516  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.540000000000001 we have the true and false labels as class1 class1
false rows of col  2  of index  758
True rows of col  0 of index  1517
Base case for index  3034  column  5
<class 'str'>
<class 'str'>
For column  5  with value 29.0 we have the true and false labels as class1 class0
false rows of col  0  of index  1517
Base case for index  3035  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.533333333333334 we have the true and false labels as class0 class0
false rows of col  5  of index  379
True rows of col  8 of index  759
Base case for index  1518  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.32 we have the true and false labels as class0 class0
false rows of col  8  of index  759
True rows of col  0 of index  1519
Base case for index  3038  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.19 we have the true and false labels as class0 class1
false rows of col  0  of index  1519
Base case for index  3039  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.4 we have the true and false labels as class1 None
false rows of col  0  of index  47
True rows of col  8 of index  95
True rows of col  8 of index  190
True rows of col  8 of index  380
True rows of col  3 of index  760
True rows of col  0 of index  1520
Base case for index  3040  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.466666666666666 we have the true and false labels as class0 class0
false rows of col  0  of index  1520
Base case for index  3041  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.215 we have the true and false labels as class1 class0
false rows of col  3  of index  760
True rows of col  5 of index  1521
True rows of col  0 of index  3042
Base case for index  6084  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.966666666666666 we have the true and false labels as class1 class0
false rows of col  0  of index  3042
Base case for index  6085  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.4 we have the true and false labels as class1 None
false rows of col  5  of index  1521
Base case for index  3043  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.733333333333334 we have the true and false labels as class0 class0
false rows of col  8  of index  380
True rows of col  0 of index  761
Base case for index  1522  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.987500000000001 we have the true and false labels as class1 class1
false rows of col  0  of index  761
True rows of col  1 of index  1523
Base case for index  3046  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.15 we have the true and false labels as class1 class1
false rows of col  1  of index  1523
True rows of col  0 of index  3047
Base case for index  6094  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.199999999999999 we have the true and false labels as class0 class1
false rows of col  0  of index  3047
Base case for index  6095  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.95 we have the true and false labels as class0 class0
false rows of col  8  of index  190
True rows of col  1 of index  381
True rows of col  0 of index  762
Base case for index  1524  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.025 we have the true and false labels as class0 class0
false rows of col  0  of index  762
Base case for index  1525  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.117142857142857 we have the true and false labels as class1 class0
false rows of col  1  of index  381
True rows of col  8 of index  763
Base case for index  1526  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3 we have the true and false labels as class0 class0
false rows of col  8  of index  763
True rows of col  2 of index  1527
Base case for index  3054  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.185 we have the true and false labels as class0 class1
false rows of col  2  of index  1527
Base case for index  3055  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7875000000000005 we have the true and false labels as class1 class1
false rows of col  8  of index  95
True rows of col  4 of index  191
True rows of col  2 of index  382
Base case for index  764  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.76 we have the true and false labels as class0 class0
false rows of col  2  of index  382
True rows of col  5 of index  765
Base case for index  1530  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.20666666666666667 we have the true and false labels as class1 class0
false rows of col  5  of index  765
Base case for index  1531  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7 we have the true and false labels as class0 class0
false rows of col  4  of index  191
True rows of col  10 of index  383
True rows of col  3 of index  766
Base case for index  1532  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.8 we have the true and false labels as class1 class1
false rows of col  3  of index  766
True rows of col  0 of index  1533
Base case for index  3066  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.185 we have the true and false labels as class0 class1
false rows of col  0  of index  1533
Base case for index  3067  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.5 we have the true and false labels as class0 None
false rows of col  10  of index  383
True rows of col  1 of index  767
Base case for index  1534  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.639999999999999 we have the true and false labels as class0 class0
false rows of col  1  of index  767
Base case for index  1535  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.9 we have the true and false labels as class0 class1
false rows of col  10  of index  1
True rows of col  1 of index  3
True rows of col  9 of index  6
True rows of col  1 of index  12
True rows of col  2 of index  24
True rows of col  1 of index  48
True rows of col  0 of index  96
Base case for index  192  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.475000000000001 we have the true and false labels as class0 class0
false rows of col  0  of index  96
True rows of col  2 of index  193
True rows of col  3 of index  386
Base case for index  772  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.45 we have the true and false labels as class0 class1
false rows of col  3  of index  386
Base case for index  773  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.675000000000001 we have the true and false labels as class0 class0
false rows of col  2  of index  193
Base case for index  387  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.8500000000000005 we have the true and false labels as class0 class0

false rows of col  1  of index  48
Base case for index  97  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.01111111111111 we have the true and false labels as class0 class0
false rows of col  2  of index  24
Base case for index  49  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.591208791208791 we have the true and false labels as class0 class0
false rows of col  1  of index  12
True rows of col  4 of index  25
True rows of col  8 of index  50
True rows of col  8 of index  100
True rows of col  3 of index  200
Base case for index  400  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.884615384615383 we have the true and false labels as class0 class0
false rows of col  3  of index  200
True rows of col  7 of index  401
Base case for index  802  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.875000000000001 we have the true and false labels as class0 class0
false rows of col  7  of index  401
Base case for index  803  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.3125 we have the true and false labels as class0 class1
false rows of col  8  of index  100
Base case for index  201  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.788571428571428 we have the true and false labels as class0 class0
false rows of col  8  of index  50
Base case for index  101  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.977922077922079 we have the true and false labels as class0 class0
false rows of col  4  of index  25
True rows of col  1 of index  51
True rows of col  0 of index  102
True rows of col  9 of index  204
True rows of col  0 of index  408
Base case for index  816  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.550000000000001 we have the true and false labels as class0 class0
false rows of col  0  of index  408
Base case for index  817  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.184 we have the true and false labels as class0 class1
false rows of col  9  of index  204
Base case for index  409  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.585714285714284 we have the true and false labels as class0 class0
false rows of col  0  of index  102
True rows of col  3 of index  205
True rows of col  2 of index  410
True rows of col  3 of index  820
Base case for index  1640  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.18 we have the true and false labels as class0 class0
false rows of col  3  of index  820
Base case for index  1641  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3999999999999995 we have the true and false labels as class0 class1
false rows of col  2  of index  410
Base case for index  821  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3100000000000005 we have the true and false labels as class0 class0
false rows of col  3  of index  205
Base case for index  411  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.0323529411764705 we have the true and false labels as class0 class0
false rows of col  1  of index  51
True rows of col  1 of index  103
True rows of col  6 of index  206
True rows of col  4 of index  412
Base case for index  824  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.807692307692308 we have the true and false labels as class0 class0
false rows of col  4  of index  412
True rows of col  0 of index  825
Base case for index  1650  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.333333333333333 we have the true and false labels as class0 class1
false rows of col  0  of index  825
Base case for index  1651  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.45 we have the true and false labels as class0 class0
false rows of col  6  of index  206
True rows of col  1 of index  413
True rows of col  8 of index  826
Base case for index  1652  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.5 we have the true and false labels as class1 class0
false rows of col  8  of index  826
Base case for index  1653  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.866666666666666 we have the true and false labels as class0 class0
false rows of col  1  of index  413
True rows of col  6 of index  827
True rows of col  2 of index  1654
Base case for index  3308  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.366666666666667 we have the true and false labels as class1 class1
false rows of col  2  of index  1654
Base case for index  3309  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.29875 we have the true and false labels as class0 class1
false rows of col  6  of index  827
True rows of col  9 of index  1655
Base case for index  3310  column  7
<class 'str'>
<class 'str'>
For column  7  with value 0.9935933333333334 we have the true and false labels as class0 class1
false rows of col  9  of index  1655
Base case for index  3311  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.050000000000001 we have the true and false labels as class0 class0
false rows of col  1  of index  103
True rows of col  8 of index  207
True rows of col  4 of index  414
Base case for index  828  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.958333333333332 we have the true and false labels as class0 class0
false rows of col  4  of index  414
True rows of col  6 of index  829
True rows of col  4 of index  1658
True rows of col  9 of index  3316
Base case for index  6632  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.75 we have the true and false labels as class1 class1
false rows of col  9  of index  3316
Base case for index  6633  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.28250000000000003 we have the true and false labels as class1 class0
false rows of col  4  of index  1658
Base case for index  3317  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.1 we have the true and false labels as class0 None
false rows of col  6  of index  829
Base case for index  1659  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.720000000000001 we have the true and false labels as class0 class0
false rows of col  8  of index  207
Base case for index  415  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.9794117647058815 we have the true and false labels as class0 class0
false rows of col  9  of index  6
True rows of col  8 of index  13
True rows of col  7 of index  26
Base case for index  52  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.971428571428571 we have the true and false labels as class0 class0
false rows of col  7  of index  26
True rows of col  3 of index  53
True rows of col  5 of index  106
Base case for index  212  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4142857142857155 we have the true and false labels as class0 class0
false rows of col  5  of index  106
True rows of col  1 of index  213
Base case for index  426  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.583333333333335 we have the true and false labels as class0 class0
false rows of col  1  of index  213
True rows of col  4 of index  427
True rows of col  4 of index  854
Base case for index  1708  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.25 we have the true and false labels as class0 class1
false rows of col  4  of index  854
Base case for index  1709  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.075 we have the true and false labels as class0 class0
false rows of col  4  of index  427
True rows of col  4 of index  855
True rows of col  1 of index  1710
Base case for index  3420  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.0 we have the true and false labels as class1 class1
false rows of col  1  of index  1710
Base case for index  3421  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.949999999999999 we have the true and false labels as class1 class0
false rows of col  4  of index  855
Base case for index  1711  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.633333333333333 we have the true and false labels as class0 class0
false rows of col  3  of index  53
True rows of col  1 of index  107
True rows of col  3 of index  214
True rows of col  10 of index  428
Base case for index  856  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.833333333333333 we have the true and false labels as class0 class1
false rows of col  10  of index  428
Base case for index  857  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.883333333333333 we have the true and false labels as class0 class0
false rows of col  3  of index  214
Base case for index  429  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.370588235294117 we have the true and false labels as class0 class0
false rows of col  1  of index  107
Base case for index  215  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.461702127659574 we have the true and false labels as class0 class0
false rows of col  8  of index  13
Base case for index  27  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.158561643835616 we have the true and false labels as class0 class0
false rows of col  1  of index  3
True rows of col  1 of index  7
True rows of col  0 of index  14
True rows of col  7 of index  28
True rows of col  7 of index  56
True rows of col  3 of index  112
True rows of col  6 of index  224
True rows of col  1 of index  448
Base case for index  896  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.26666666666666666 we have the true and false labels as class0 class1
false rows of col  1  of index  448
Base case for index  897  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.057142857142857 we have the true and false labels as class0 class0
false rows of col  6  of index  224
Base case for index  449  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.172222222222222 we have the true and false labels as class0 class0
false rows of col  3  of index  112
True rows of col  10 of index  225
True rows of col  7 of index  450
Base case for index  900  column  6
<class 'str'>
<class 'str'>
For column  6  with value 145.33333333333334 we have the true and false labels as class1 class0
false rows of col  7  of index  450
Base case for index  901  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.709999999999999 we have the true and false labels as class0 class0
false rows of col  10  of index  225
True rows of col  9 of index  451
True rows of col  3 of index  902
Base case for index  1804  column  3
<class 'str'>
<class 'str'>
For column  3  with value 14.719999999999999 we have the true and false labels as class0 class1
false rows of col  3  of index  902
Base case for index  1805  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.55 we have the true and false labels as class0 class0
false rows of col  9  of index  451
True rows of col  8 of index  903
Base case for index  1806  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.722222222222222 we have the true and false labels as class1 class1
false rows of col  8  of index  903
Base case for index  1807  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.24 we have the true and false labels as class1 class0
false rows of col  7  of index  56
True rows of col  5 of index  113
True rows of col  9 of index  226
True rows of col  8 of index  452
True rows of col  0 of index  904
True rows of col  2 of index  1808
Base case for index  3616  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.1 we have the true and false labels as class0 class1
false rows of col  2  of index  1808
Base case for index  3617  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.975 we have the true and false labels as class0 class0
false rows of col  0  of index  904
Base case for index  1809  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.2375 we have the true and false labels as class0 class0
false rows of col  8  of index  452
True rows of col  5 of index  905
Base case for index  1810  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.9 we have the true and false labels as class0 None
false rows of col  5  of index  905
True rows of col  0 of index  1811
Base case for index  3622  column  3
<class 'str'>
<class 'str'>
For column  3  with value 12.799999999999999 we have the true and false labels as class0 class1
false rows of col  0  of index  1811
Base case for index  3623  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.160000000000001 we have the true and false labels as class1 class1
false rows of col  9  of index  226
Base case for index  453  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.4879999999999995 we have the true and false labels as class0 class0
false rows of col  5  of index  113
True rows of col  1 of index  227
True rows of col  8 of index  454
True rows of col  4 of index  908
Base case for index  1816  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.525 we have the true and false labels as class0 class0
false rows of col  4  of index  908
Base case for index  1817  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.26 we have the true and false labels as class1 class0
false rows of col  8  of index  454
Base case for index  909  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.836363636363637 we have the true and false labels as class0 class0
false rows of col  1  of index  227
Base case for index  455  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.913043478260868 we have the true and false labels as class0 class0
false rows of col  7  of index  28
True rows of col  8 of index  57
True rows of col  5 of index  114
True rows of col  6 of index  228
Base case for index  456  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.1499999999999995 we have the true and false labels as class0 class0
false rows of col  6  of index  228
True rows of col  1 of index  457
True rows of col  4 of index  914
Base case for index  1828  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.58 we have the true and false labels as class0 class0
false rows of col  4  of index  914
Base case for index  1829  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.949999999999999 we have the true and false labels as class1 class0
false rows of col  1  of index  457
True rows of col  3 of index  915
Base case for index  1830  column  3
<class 'str'>
<class 'str'>
For column  3  with value 7.300000000000002 we have the true and false labels as class1 class0
false rows of col  3  of index  915
Base case for index  1831  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.75 we have the true and false labels as class0 class1
false rows of col  5  of index  114
True rows of col  4 of index  229
True rows of col  8 of index  458

True rows of col  7 of index  916
Base case for index  1832  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.575 we have the true and false labels as class0 class0
false rows of col  7  of index  916
Base case for index  1833  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.37 we have the true and false labels as class1 class0
false rows of col  8  of index  458
Base case for index  917  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.425 we have the true and false labels as class0 class0
false rows of col  4  of index  229
Base case for index  459  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.389473684210526 we have the true and false labels as class0 class0
false rows of col  8  of index  57
True rows of col  8 of index  115
Base case for index  230  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.647999999999999 we have the true and false labels as class0 class0
false rows of col  8  of index  115
True rows of col  3 of index  231
True rows of col  0 of index  462
True rows of col  6 of index  924
Base case for index  1848  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.5 we have the true and false labels as class0 class0
false rows of col  6  of index  924
Base case for index  1849  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.034333333333333334 we have the true and false labels as class0 class1
false rows of col  0  of index  462
Base case for index  925  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.2625 we have the true and false labels as class0 class0
false rows of col  3  of index  231
Base case for index  463  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.157142857142857 we have the true and false labels as class0 class0
false rows of col  0  of index  14
True rows of col  10 of index  29
True rows of col  8 of index  58
True rows of col  3 of index  116
True rows of col  4 of index  232
Base case for index  464  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.247058823529412 we have the true and false labels as class0 class0
false rows of col  4  of index  232
True rows of col  4 of index  465
Base case for index  930  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3909090909090915 we have the true and false labels as class0 class0
false rows of col  4  of index  465
True rows of col  2 of index  931
Base case for index  1862  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.035166666666666666 we have the true and false labels as class1 class0
false rows of col  2  of index  931
Base case for index  1863  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.225 we have the true and false labels as class0 class0
false rows of col  3  of index  116
True rows of col  9 of index  233
True rows of col  1 of index  466
Base case for index  932  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.37 we have the true and false labels as class0 class0
false rows of col  1  of index  466
True rows of col  9 of index  933
Base case for index  1866  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.119999999999999 we have the true and false labels as class0 class0
false rows of col  9  of index  933
True rows of col  2 of index  1867
Base case for index  3734  column  10
<class 'str'>
<class 'str'>
For column  10  with value 10.175 we have the true and false labels as class1 class0
false rows of col  2  of index  1867
Base case for index  3735  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.625 we have the true and false labels as class1 class0
false rows of col  9  of index  233
True rows of col  5 of index  467
True rows of col  2 of index  934
True rows of col  0 of index  1868
Base case for index  3736  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4 we have the true and false labels as class1 class0
false rows of col  0  of index  1868
Base case for index  3737  column  0
<class 'str'>
<class 'str'>
For column  0  with value 4.9 we have the true and false labels as class0 class0
false rows of col  2  of index  934
Base case for index  1869  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.1 we have the true and false labels as class1 class1
false rows of col  5  of index  467
True rows of col  5 of index  935
Base case for index  1870  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.26 we have the true and false labels as class0 class0
false rows of col  5  of index  935
True rows of col  2 of index  1871
Base case for index  3742  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.449999999999999 we have the true and false labels as class0 class1
false rows of col  2  of index  1871
Base case for index  3743  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.949999999999999 we have the true and false labels as class0 class0
false rows of col  8  of index  58
True rows of col  9 of index  117
True rows of col  3 of index  234
True rows of col  8 of index  468
True rows of col  0 of index  936
True rows of col  8 of index  1872
Base case for index  3744  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.733333333333333 we have the true and false labels as class0 class0
false rows of col  8  of index  1872
Base case for index  3745  column  3
<class 'str'>
<class 'str'>
For column  3  with value 11.233333333333334 we have the true and false labels as class0 class1
false rows of col  0  of index  936
Base case for index  1873  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.65 we have the true and false labels as class1 class1
false rows of col  8  of index  468
Base case for index  937  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.625 we have the true and false labels as class0 class0
false rows of col  3  of index  234
Base case for index  469  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.222222222222222 we have the true and false labels as class0 class0
false rows of col  9  of index  117
Base case for index  235  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.237500000000001 we have the true and false labels as class0 class0
false rows of col  10  of index  29
True rows of col  9 of index  59
True rows of col  6 of index  118
Base case for index  236  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.50759493670886 we have the true and false labels as class0 class0
false rows of col  6  of index  118
True rows of col  2 of index  237
True rows of col  7 of index  474
Base case for index  948  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.4333333333333345 we have the true and false labels as class0 class0
false rows of col  7  of index  474
True rows of col  7 of index  949
Base case for index  1898  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.533333333333334 we have the true and false labels as class0 class0
false rows of col  7  of index  949
Base case for index  1899  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.2425 we have the true and false labels as class1 class0
false rows of col  2  of index  237
Base case for index  475  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.316666666666667 we have the true and false labels as class0 class0
false rows of col  9  of index  59
Base case for index  119  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.314615384615386 we have the true and false labels as class0 class0
false rows of col  1  of index  7
True rows of col  4 of index  15
True rows of col  7 of index  30
True rows of col  10 of index  60
True rows of col  3 of index  120
True rows of col  0 of index  240
True rows of col  8 of index  480
True rows of col  0 of index  960
Base case for index  1920  column  10
<class 'str'>
<class 'str'>
For column  10  with value 9.6 we have the true and false labels as class0 class1
false rows of col  0  of index  960
True rows of col  2 of index  1921
Base case for index  3842  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.199999999999999 we have the true and false labels as class0 class0
false rows of col  2  of index  1921
Base case for index  3843  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.05 we have the true and false labels as class1 class0
false rows of col  8  of index  480
Base case for index  961  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.0 we have the true and false labels as class0 class0
false rows of col  0  of index  240
True rows of col  9 of index  481
Base case for index  962  column  5
<class 'str'>
<class 'str'>
For column  5  with value 26.5 we have the true and false labels as class1 class0
false rows of col  9  of index  481
Base case for index  963  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.654545454545453 we have the true and false labels as class0 class0
false rows of col  3  of index  120
Base case for index  241  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.172727272727272 we have the true and false labels as class0 class0
false rows of col  10  of index  60
True rows of col  2 of index  121
True rows of col  5 of index  242
Base case for index  484  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.5583333333333345 we have the true and false labels as class0 class0
false rows of col  5  of index  242
True rows of col  0 of index  485
Base case for index  970  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.566666666666666 we have the true and false labels as class1 class1
false rows of col  0  of index  485
True rows of col  0 of index  971
Base case for index  1942  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.949999999999999 we have the true and false labels as class0 class0
false rows of col  0  of index  971
Base case for index  1943  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.6 we have the true and false labels as class0 class1
false rows of col  2  of index  121
True rows of col  8 of index  243
Base case for index  486  column  6
<class 'str'>
<class 'str'>
For column  6  with value 204.93333333333334 we have the true and false labels as class1 class0
false rows of col  8  of index  243
Base case for index  487  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.172222222222223 we have the true and false labels as class1 class1
false rows of col  7  of index  30
True rows of col  7 of index  61
True rows of col  9 of index  122
Base case for index  244  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.236000000000001 we have the true and false labels as class0 class0
false rows of col  9  of index  122
True rows of col  2 of index  245
Base case for index  490  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.941666666666666 we have the true and false labels as class0 class0
false rows of col  2  of index  245
True rows of col  5 of index  491
True rows of col  1 of index  982
Base case for index  1964  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.221428571428571 we have the true and false labels as class0 class0
false rows of col  1  of index  982
Base case for index  1965  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.12 we have the true and false labels as class0 class1
false rows of col  5  of index  491
True rows of col  4 of index  983

Base case for index  1966  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.3 we have the true and false labels as class1 None
false rows of col  4  of index  983
True rows of col  1 of index  1967
Base case for index  3934  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.3379999999999996 we have the true and false labels as class1 class0
false rows of col  1  of index  1967
Base case for index  3935  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.0200000000000005 we have the true and false labels as class0 class0
false rows of col  7  of index  61
True rows of col  5 of index  123
True rows of col  9 of index  246
True rows of col  4 of index  492
True rows of col  6 of index  984
Base case for index  1968  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.092 we have the true and false labels as class0 class1
false rows of col  6  of index  984
Base case for index  1969  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.1 we have the true and false labels as class0 None
false rows of col  4  of index  492
True rows of col  6 of index  985
True rows of col  1 of index  1970
Base case for index  3940  column  6
<class 'str'>
<class 'str'>
For column  6  with value 145.0 we have the true and false labels as class1 class0
false rows of col  1  of index  1970
Base case for index  3941  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.25 we have the true and false labels as class1 class1
false rows of col  6  of index  985
Base case for index  1971  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.366666666666667 we have the true and false labels as class1 class1
false rows of col  9  of index  246
True rows of col  6 of index  493
True rows of col  0 of index  986
Base case for index  1972  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.0800000000000005 we have the true and false labels as class1 class0
false rows of col  0  of index  986
Base case for index  1973  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.333333333333333 we have the true and false labels as class0 class0
false rows of col  6  of index  493
Base case for index  987  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.681818181818182 we have the true and false labels as class0 class0
false rows of col  5  of index  123
True rows of col  7 of index  247
Base case for index  494  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.376470588235295 we have the true and false labels as class0 class0
false rows of col  7  of index  247
True rows of col  3 of index  495
True rows of col  0 of index  990
Base case for index  1980  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.65 we have the true and false labels as class1 class0
false rows of col  0  of index  990
Base case for index  1981  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.15 we have the true and false labels as class0 class0
false rows of col  3  of index  495
Base case for index  991  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.966666666666668 we have the true and false labels as class0 class0
false rows of col  4  of index  15
True rows of col  9 of index  31
True rows of col  6 of index  62
True rows of col  4 of index  124
True rows of col  8 of index  248
Base case for index  496  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.82 we have the true and false labels as class0 class0
false rows of col  8  of index  248
True rows of col  0 of index  497
True rows of col  3 of index  994
Base case for index  1988  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.566666666666667 we have the true and false labels as class0 class0
false rows of col  3  of index  994
True rows of col  4 of index  1989
Base case for index  3978  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.533333333333333 we have the true and false labels as class0 class0
false rows of col  4  of index  1989
Base case for index  3979  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.1375 we have the true and false labels as class1 class0
false rows of col  0  of index  497
True rows of col  9 of index  995
Base case for index  1990  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.779999999999999 we have the true and false labels as class0 class1
false rows of col  9  of index  995
Base case for index  1991  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.561538461538461 we have the true and false labels as class0 class0
false rows of col  4  of index  124
True rows of col  2 of index  249
True rows of col  1 of index  498
Base case for index  996  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.2 we have the true and false labels as class0 class0
false rows of col  1  of index  498
Base case for index  997  column  3
<class 'str'>
<class 'str'>
For column  3  with value 6.1 we have the true and false labels as class1 class0
false rows of col  2  of index  249
True rows of col  1 of index  499
Base case for index  998  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.68 we have the true and false labels as class1 class1
false rows of col  1  of index  499
True rows of col  3 of index  999
Base case for index  1998  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.333333333333333 we have the true and false labels as class0 class1
false rows of col  3  of index  999
Base case for index  1999  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.9 we have the true and false labels as class0 class0
false rows of col  6  of index  62
True rows of col  5 of index  125
True rows of col  1 of index  250
True rows of col  9 of index  500
Base case for index  1000  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.990909090909091 we have the true and false labels as class1 class1
false rows of col  9  of index  500
True rows of col  9 of index  1001
True rows of col  9 of index  2002
Base case for index  4004  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.550000000000001 we have the true and false labels as class1 class0
false rows of col  9  of index  2002
Base case for index  4005  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.68 we have the true and false labels as class1 class1
false rows of col  9  of index  1001
True rows of col  0 of index  2003
Base case for index  4006  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.75 we have the true and false labels as class1 class0
false rows of col  0  of index  2003
Base case for index  4007  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.233333333333334 we have the true and false labels as class0 class0
false rows of col  1  of index  250
True rows of col  3 of index  501
True rows of col  10 of index  1002
Base case for index  2004  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.533333333333334 we have the true and false labels as class1 class1
false rows of col  10  of index  1002
Base case for index  2005  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.5 we have the true and false labels as class1 class0
false rows of col  3  of index  501
True rows of col  9 of index  1003
True rows of col  0 of index  2006
True rows of col  0 of index  4012
Base case for index  8024  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.35 we have the true and false labels as class1 class0
false rows of col  0  of index  4012
Base case for index  8025  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 7.2 we have the true and false labels as class0 None
false rows of col  0  of index  2006
Base case for index  4013  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 6.7 we have the true and false labels as class1 None
false rows of col  9  of index  1003
Base case for index  2007  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.266666666666667 we have the true and false labels as class0 class0
false rows of col  5  of index  125
True rows of col  6 of index  251
True rows of col  0 of index  502
True rows of col  2 of index  1004
Base case for index  2008  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.7 we have the true and false labels as class0 class0
false rows of col  2  of index  1004
Base case for index  2009  column  1
<class 'str'>
<class 'str'>
For column  1  with value 0.17333333333333334 we have the true and false labels as class1 class0
false rows of col  0  of index  502
Base case for index  1005  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.650000000000001 we have the true and false labels as class0 class0
false rows of col  6  of index  251
True rows of col  8 of index  503
True rows of col  7 of index  1006
Base case for index  2012  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.300000000000001 we have the true and false labels as class0 class0
false rows of col  7  of index  1006
True rows of col  0 of index  2013
Base case for index  4026  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3 we have the true and false labels as class1 class1
false rows of col  0  of index  2013
Base case for index  4027  column  8
<class 'str'>
<class 'str'>
For column  8  with value 3.403333333333333 we have the true and false labels as class1 class0
false rows of col  8  of index  503
True rows of col  3 of index  1007
True rows of col  1 of index  2014
Base case for index  4028  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.85 we have the true and false labels as class0 class1
false rows of col  1  of index  2014
Base case for index  4029  column  0
<class 'NoneType'>
<class 'str'>
For column  0  with value 8.6 we have the true and false labels as class0 None
false rows of col  3  of index  1007
Base case for index  2015  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.071428571428571 we have the true and false labels as class0 class0
false rows of col  9  of index  31
True rows of col  10 of index  63
True rows of col  3 of index  126
True rows of col  4 of index  252
True rows of col  9 of index  504
True rows of col  6 of index  1008
True rows of col  2 of index  2016
Base case for index  4032  column  2
<class 'str'>
<class 'str'>
For column  2  with value 0.5299999999999999 we have the true and false labels as class1 class0
false rows of col  2  of index  2016
Base case for index  4033  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.728571428571428 we have the true and false labels as class0 class0
false rows of col  6  of index  1008
True rows of col  2 of index  2017
Base case for index  4034  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.7 we have the true and false labels as class0 class0
false rows of col  2  of index  2017
Base case for index  4035  column  5
<class 'str'>
<class 'str'>
For column  5  with value 27.8 we have the true and false labels as class1 class0
false rows of col  9  of index  504
Base case for index  1009  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.874999999999999 we have the true and false labels as class0 class0
false rows of col  4  of index  252
True rows of col  6 of index  505
True rows of col  7 of index  1010
Base case for index  2020  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.225 we have the true and false labels as class0 class1
false rows of col  7  of index  1010
Base case for index  2021  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.683333333333334 we have the true and false labels as class0 class0
false rows of col  6  of index  505
True rows of col  3 of index  1011
Base case for index  2022  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.666666666666668 we have the true and false labels as class1 class1
false rows of col  3  of index  1011
True rows of col  2 of index  2023
Base case for index  4046  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.6499999999999995 we have the true and false labels as class0 class0
false rows of col  2  of index  2023
Base case for index  4047  column  6
<class 'str'>
<class 'str'>
For column  6  with value 111.0 we have the true and false labels as class0 class1
false rows of col  3  of index  126
True rows of col  4 of index  253
True rows of col  2 of index  506
True rows of col  8 of index  1012
Base case for index  2024  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.25 we have the true and false labels as class0 class0
false rows of col  8  of index  1012
True rows of col  2 of index  2025
Base case for index  4050  column  3
<class 'str'>
<class 'str'>
For column  3  with value 1.52 we have the true and false labels as class0 class1
false rows of col  2  of index  2025
True rows of col  1 of index  4051
Base case for index  8102  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.640000000000001 we have the true and false labels as class0 class0
false rows of col  1  of index  4051
Base case for index  8103  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.033333333333333 we have the true and false labels as class0 class1
false rows of col  2  of index  506
True rows of col  0 of index  1013
True rows of col  4 of index  2026
Base case for index  4052  column  7
<class 'str'>
<class 'str'>
For column  7  with value 0.9936119999999999 we have the true and false labels as class0 class1
false rows of col  4  of index  2026
Base case for index  4053  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.85 we have the true and false labels as class0 class0
false rows of col  0  of index  1013
Base case for index  2027  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.8999999999999995 we have the true and false labels as class0 class0
false rows of col  4  of index  253
True rows of col  10 of index  507
True rows of col  6 of index  1014
Base case for index  2028  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.3875 we have the true and false labels as class0 class0
false rows of col  6  of index  1014
True rows of col  0 of index  2029
Base case for index  4058  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.433333333333334 we have the true and false labels as class0 class0
false rows of col  0  of index  2029
Base case for index  4059  column  0
<class 'str'>
<class 'str'>
For column  0  with value 7.433333333333334 we have the true and false labels as class1 class0
false rows of col  10  of index  507
Base case for index  1015  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.936842105263159 we have the true and false labels as class0 class0
false rows of col  10  of index  63
True rows of col  10 of index  127
True rows of col  8 of index  254
True rows of col  2 of index  508
True rows of col  2 of index  1016
Base case for index  2032  column  4
<class 'str'>
<class 'str'>
For column  4  with value 0.043666666666666666 we have the true and false labels as class0 class1
false rows of col  2  of index  1016
True rows of col  2 of index  2033
Base case for index  4066  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.75 we have the true and false labels as class0 class0
false rows of col  2  of index  2033
Base case for index  4067  column  5
<class 'str'>
<class 'str'>
For column  5  with value 28.6 we have the true and false labels as class1 class0
false rows of col  2  of index  508
Base case for index  1017  column  0
<class 'str'>
<class 'str'>
For column  0  with value 5.840000000000001 we have the true and false labels as class0 class0
false rows of col  8  of index  254
True rows of col  0 of index  509
True rows of col  5 of index  1018
Base case for index  2036  column  0
<class 'str'>
<class 'str'>

For column  0  with value 7.520000000000001 we have the true and false labels as class0 class0
false rows of col  5  of index  1018
True rows of col  1 of index  2037
Base case for index  4074  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.25 we have the true and false labels as class0 class1
false rows of col  1  of index  2037
Base case for index  4075  column  0
<class 'str'>
<class 'str'>
For column  0  with value 8.925 we have the true and false labels as class0 class0
false rows of col  0  of index  509
Base case for index  1019  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.744444444444445 we have the true and false labels as class0 class0
false rows of col  10  of index  127
Base case for index  255  column  0
<class 'str'>
<class 'str'>
For column  0  with value 6.818421052631578 we have the true and false labels as class0 class0